//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment_()
        {
            this.Reply_ = new HashSet<Reply_>();
        }
    
        public int id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date_message { get; set; }
        public Nullable<int> classe_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> sub_chapter_id { get; set; }
    
        public virtual User_ User_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reply_> Reply_ { get; set; }
        public virtual Class_ Class_ { get; set; }
        public virtual Subchapter_ Subchapter_ { get; set; }
    }
}
