//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elearningEntities : DbContext
    {
        public elearningEntities()
            : base("name=elearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Chapter_> Chapter_ { get; set; }
        public virtual DbSet<Group_> Group_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
        public virtual DbSet<Comment_> Comment_ { get; set; }
        public virtual DbSet<Reply_> Reply_ { get; set; }
        public virtual DbSet<Class_> Class_ { get; set; }
        public virtual DbSet<Theme_> Theme_ { get; set; }
        public virtual DbSet<Seen_> Seen_ { get; set; }
        public virtual DbSet<Video_> Video_ { get; set; }
        public virtual DbSet<Subchapter_> Subchapter_ { get; set; }
    }
}
