//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class User_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_()
        {
            this.Comment_ = new HashSet<Comment_>();
        }

        public int id { get; set; }
        [Display(Name = "Nom")]
        public string last_name { get; set; }
        [Display(Name = "Prénom")]
        public string first_name { get; set; }
        [Display(Name = "E-mail")]
        public string mail { get; set; }
        [Display(Name = "Type")]
        public Nullable<int> type { get; set; }
        [Display(Name = "Classe")]
        public Nullable<int> group_id { get; set; }
        public string user_asp_net_id { get; set; }
        public string sexe { get; set; }
        [Display(Name = "Compte actif")]
        public Nullable<bool> user_validate { get; set; }
        public string SelectedType { get; set; }
        public List<SelectListItem> ListType { get; set; }
        public string SelectedSexe { get; set; }
        public List<SelectListItem> ListSexe { get; set; }
        public bool CheckActive { get; set; }
        public bool CheckDesactive { get; set; }
        public string MessageActivGlobal { get; set; }

        public virtual Group_ Group_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_> Comment_ { get; set; }
    }
}
