//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_
    {
        public int id { get; set; }
        public string url_video { get; set; }
        public Nullable<double> time_start { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> chapter_id { get; set; }
    }
}
