//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video_
    {
        public int id { get; set; }
        [Display(Name = "Nom")]
        public string name { get; set; }
        public Nullable<int> file_size { get; set; }
        [Display(Name = "Chemin du fichier")]
        public string file_path { get; set; }
        public int subchapter_id { get; set; }

        public virtual Subchapter_ Subchapter_ { get; set; }
    }
}
